name: ray-tracing-hs
version: 0.1.0.0
github: "farbodsz/ray-tracing-hs"
author: "Farbod Salamat-Zadeh"
copyright: "2023 Farbod Salamat-Zadeh"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: Implementation of Ray Tracing in One Weekend in Haskell
category: Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/farbodsz/ray-tracing-hs#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  ray-tracing-hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ray-tracing-hs

tests:
  ray-tracing-hs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ray-tracing-hs
